[package]
name = "main"
version = "1.0.0"
authors = ["Diego.Pacheco"]
edition = "2018"

[dependencies]
pb-jelly = "0.0.1"

[build-dependencies]
pb-jelly-gen = "0.0.1"
protobuf = { version = "2", features = ["with-bytes"] }
protoc-rust = "1.5"