[tasks.A]
dependencies = ["B", "C"]

[tasks.B]
dependencies = ["D"]

[tasks.C]
dependencies = ["D"]

[tasks.D]
script = [
    "echo hello"
]

[tasks.code]
script_runner = "@duckscript"
script = [
'''
ls -lsa
'''
]